from .auth_routes import auth_bp
from .user_routes import user_bp
from .assessment_routes import assessment_bp
from .request_routes import request_bp
from .session_routes import session_bp
from .assignment_routes import assignment_bp
from .support_routes import support_bp
from .template_routes import template_bp
from .admin_routes import admin_bp
from .admin_auth_routes import admin_auth_bp
from .admin_assessment_routes import admin_assessment_bp
