"""empty message

Revision ID: b07df24ca84e
Revises: fe0a5543239e
Create Date: 2024-01-19 15:39:02.388050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b07df24ca84e'
down_revision = 'fe0a5543239e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_tutoring_time', sa.String(), nullable=False, server_default="Always available"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('free_tutoring_time')

    # ### end Alembic commands ###
